export const bases = [
  { fileName: "Classic Blue.png", name: "Classic Blue" },
  { fileName: "Classic Green.png", name: "Classic Green" },
  { fileName: "Classic Orange.png", name: "Classic Orange" },
  { fileName: "Classic Pink.png", name: "Classic Pink" },
  { fileName: "Classic Purple.png", name: "Classic Purple" },
  { fileName: "Classic Tan.png", name: "Classic Tan" },
  { fileName: "Gold Plated.PNG", name: "Gold Plated" },
  { fileName: "Leopard Spots Blue.PNG", name: "Leopard Spots Blue" },
  { fileName: "Leopard Spots Tan.PNG", name: "Leopard Spots Tan" },
  { fileName: "Magma.PNG", name: "Magma" },
  { fileName: "Mecha Graft.PNG", name: "Mecha Graft" },
  { fileName: "Radioactive Green.PNG", name: "Radioactive Green" },
  { fileName: "Radioactive Pink.PNG", name: "Radioactive Pink" },
  { fileName: "Tiger Stripes.PNG", name: "Tiger Stripes" },
  { fileName: "Trippin.PNG", name: "Trippin" },
  { fileName: "Zombie.PNG", name: "Zombie" },
];

export const surfboards = [
  { fileName: "Comet Storm Day.PNG", name: "Comet Storm Day" },
  { fileName: "Comet Storm Night.PNG", name: "Comet Storm Night" },
  { fileName: "Dino Skull Blue.png", name: "Dino Skull Blue" },
  { fileName: "Dino Skull Brown.png", name: "Dino Skull Brown" },
  { fileName: "Dino Skull Green.png", name: "Dino Skull Green" },
  { fileName: "Dino Skull Purple.png", name: "Dino Skull Purple" },
  { fileName: "Dinosaur Hieroglyphics.PNG", name: "Dinosaur Hieroglyphics" },
  { fileName: "Etching Green.png", name: "Etching Green" },
  { fileName: "Etching Tan.png", name: "Etching Tan" },
  { fileName: "Flames.png", name: "Flames" },
  { fileName: "Fuku Burger.png", name: "Fuku Burger" },
  { fileName: "Green With Blue Stripe.png", name: "Green With Blue Stripe" },
  { fileName: "Orange With Blue Stripe.png", name: "Orange With Blue Stripe" },
  {
    fileName: "Purple With Purple Stripe.png",
    name: "Purple With Purple Stripe",
  },
  { fileName: "Rainbow.PNG", name: "Rainbow" },
  { fileName: "Volcano.png", name: "Volcano" },
];

export const backgrounds = [
  { fileName: "Blue Sky Common.png", name: "Blue Sky Common" },
  { fileName: "Comet Day.PNG", name: "Comet Day" },
  { fileName: "Comet Night.PNG", name: "Comet Night" },
  { fileName: "Dusk Volcano.png", name: "Dusk Volcano" },
  { fileName: "Night Volcano.png", name: "Night Volcano" },
  {
    fileName: "Pink Sky With Pterodactyls.png",
    name: "Pink Sky With Pterodactyls",
  },
  { fileName: "Starry Night.png", name: "Starry Night" },
  { fileName: "Sunset.png", name: "Sunset" },
];

export const fins = [
  { fileName: "Ammonite Blue.PNG", name: "Ammonite Blue" },
  { fileName: "Ammonite Brown.PNG", name: "Ammonite Brown" },
  { fileName: "Ammonite Magenta.PNG", name: "Ammonite Magenta" },
  { fileName: "Lagoon Creature Hand.PNG", name: "Lagoon Creature Hand" },
  { fileName: "Lobster Blue.PNG", name: "Lobster Blue" },
  { fileName: "Lobster Brown.PNG", name: "Lobster Brown" },
  { fileName: "Lobster Cooked.PNG", name: "Lobster Cooked" },
  { fileName: "Lobster Red.PNG", name: "Lobster Red" },
  { fileName: "Octopus Arm Brown.PNG", name: "Octopus Arm Brown" },
  { fileName: "Octopus Arm Green.PNG", name: "Octopus Arm Green" },
  { fileName: "Octopus Arm Pink.PNG", name: "Octopus Arm Pink" },
  { fileName: "Periscope.PNG", name: "Periscope" },
  { fileName: "Shark Blue.PNG", name: "Shark Blue" },
  { fileName: "Shark Gray.png", name: "Shark Gray" },
  { fileName: "Tiger Shark.PNG", name: "Tiger Shark" },
];

export const eyes = [
  { fileName: "Baked.PNG", name: "Baked" },
  { fileName: "Band-Aids On Face.PNG", name: "Band-Aids On Face" },
  { fileName: "Classic Surf Shades.PNG", name: "Classic Surf Shades" },
  { fileName: "Demonic.PNG", name: "Demonic" },
  { fileName: "Eyepatch Egyptian.PNG", name: "Eyepatch Egyptian" },
  { fileName: "Eyepatch Gems.PNG", name: "Eyepatch Gems" },
  { fileName: "Glacier Blue.PNG", name: "Glacier Blue" },
  { fileName: "Glacier Orange.PNG", name: "Glacier Orange" },
  { fileName: "Glacier Purple.PNG", name: "Glacier Purple" },
  { fileName: "Heart Shades.PNG", name: "Heart Shades" },
  { fileName: "LOL Crying.PNG", name: "LOL Crying" },
  { fileName: "Macho Shades.PNG", name: "Macho Shades" },
  { fileName: "Metal Endoskeleton.PNG", name: "Metal Endoskeleton" },
  { fileName: "Monocle.PNG", name: "Monocle" },
  { fileName: "Nerdy Glasses.PNG", name: "Nerdy Glasses" },
  { fileName: "Planet Earth.PNG", name: "Planet Earth" },
  { fileName: "Rainbow Shades.PNG", name: "Rainbow Shades" },
  { fileName: "Red Spiral Wacked-Out.PNG", name: "Red Spiral Wacked-Out" },
  { fileName: "Serpentine.PNG", name: "Serpentine" },
  { fileName: "Sherbet Shades.PNG", name: "Sherbet Shades" },
];

export const accessories = [
  {
    fileName: "Baseball Cap Fuku Burger.PNG",
    name: "Baseball Cap Fuku Burger",
  },
  { fileName: "Baseball Cap Jaws.PNG", name: "Baseball Cap Jaws" },
  {
    fileName: "Baseball Cap Surfosaurs Logo.PNG",
    name: "Baseball Cap Surfosaurs Logo",
  },
  { fileName: "Biggie Crown.PNG", name: "Biggie Crown" },
  { fileName: "Bucket Hat Blue Dino.PNG", name: "Bucket Hat Blue Dino" },
  { fileName: "Bucket Hat Blue Whale.PNG", name: "Bucket Hat Blue Whale" },
  { fileName: "Bucket Hat Green Whale.PNG", name: "Bucket Hat Green Whale" },
  { fileName: "Bucket Hat Pink Dino.PNG", name: "Bucket Hat Pink Dino" },
  { fileName: "Bucket Hat Red Whale.PNG", name: "Bucket Hat Red Whale" },
  { fileName: "Captain's Hat.PNG", name: "Captain's Hat" },
  { fileName: "Cowboy Hat Brown.PNG", name: "Cowboy Hat Brown" },
  { fileName: "Cowboy Hat Feather.PNG", name: "Cowboy Hat Feather" },
  { fileName: "Durag.PNG", name: "Durag" },
  { fileName: "Fez Fancy Purple.PNG", name: "Fez Fancy Purple" },
  { fileName: "Fez Maroon.PNG", name: "Fez Maroon" },
  { fileName: "GoPro Snout Clip.PNG", name: "GoPro Snout Clip" },
  { fileName: "Outback Hat.PNG", name: "Outback Hat" },
  { fileName: "Pork Pie Hat Charcoal.PNG", name: "Pork Pie Hat Charcoal" },
  { fileName: "Pork Pie Hat Straw.PNG", name: "Pork Pie Hat Straw" },
  { fileName: "Straw Hat.PNG", name: "Straw Hat" },
  { fileName: "Sun Visor Purple.PNG", name: "Sun Visor Purple" },
  { fileName: "Sun Visor Red.PNG", name: "Sun Visor Red" },
  { fileName: "Sun Visor Yellow.PNG", name: "Sun Visor Yellow" },
  { fileName: "Tail Bandana Black.PNG", name: "Tail Bandana Black" },
  { fileName: "Tail Bandana Blue.PNG", name: "Tail Bandana Blue" },
  { fileName: "Tail Bandana Red.PNG", name: "Tail Bandana Red" },
  { fileName: "Tail Bandana Yellow.PNG", name: "Tail Bandana Yellow" },
  { fileName: "Water Wings Green.PNG", name: "Water Wings Green" },
  { fileName: "Water Wings Orange.PNG", name: "Water Wings Orange" },
  { fileName: "Water Wings Purple.PNG", name: "Water Wings Purple" },
];

export const jewelry = [
  { fileName: "Big Rings.PNG", name: "Big Rings" },
  { fileName: "Brass Knuckles.PNG", name: "Brass Knuckles" },
  { fileName: "Calculator Wristwatch.PNG", name: "Calculator Wristwatch" },
  { fileName: "Digital Wristwatch.PNG", name: "Digital Wristwatch" },
  { fileName: "Eyebrow Piercing.PNG", name: "Eyebrow Piercing" },
  { fileName: "Gold Anklet.PNG", name: "Gold Anklet" },
  { fileName: "Gold Chain With Bone.PNG", name: "Gold Chain With Bone" },
  { fileName: "Gold Chain With Skull.PNG", name: "Gold Chain With Skull" },
  { fileName: "Gold Chain.PNG", name: "Gold Chain" },
  { fileName: "Gold Wristwatch.PNG", name: "Gold Wristwatch" },
  { fileName: "House Arrest Ankle Band.PNG", name: "House Arrest Ankle Band" },
  { fileName: "Logo Necklace Anklet.png", name: "Logo Necklace Anklet" },
  {
    fileName: "Megalodon Tooth Necklace.png",
    name: "Megalodon Tooth Necklace",
  },
  { fileName: "Nose Ring Gold.PNG", name: "Nose Ring Gold" },
  { fileName: "Nose Ring Silver.PNG", name: "Nose Ring Silver" },
  { fileName: "Shell Necklace Aqua.PNG", name: "Shell Necklace Aqua" },
  { fileName: "Shell Necklace Green.PNG", name: "Shell Necklace Green" },
  { fileName: "Shell Necklace Rainbow.PNG", name: "Shell Necklace Rainbow" },
  { fileName: "Shell Necklace White.PNG", name: "Shell Necklace White" },
  { fileName: "Silver Anklet.PNG", name: "Silver Anklet" },
  { fileName: "Spiked Collar.PNG", name: "Spiked Collar" },
  { fileName: "Toe Rings.PNG", name: "Toe Rings" },
  { fileName: "Woven Bracelets.PNG", name: "Woven Bracelets" },
];

export const mouths = [
  { fileName: "Braces.PNG", name: "Braces" },
  { fileName: "Buckteeth Gold.PNG", name: "Buckteeth Gold" },
  { fileName: "Buckteeth Sharp.PNG", name: "Buckteeth Sharp" },
  { fileName: "Cigar.PNG", name: "Cigar" },
  { fileName: "Gold And Diamond Grill.PNG", name: "Gold And Diamond Grill" },
  { fileName: "Gold Teeth.png", name: "Gold Teeth" },
  { fileName: "Joint.PNG", name: "Joint" },
  { fileName: "Octopus Tentacle Green.PNG", name: "Octopus Tentacle Green" },
  { fileName: "Octopus Tentacle Pink.PNG", name: "Octopus Tentacle Pink" },
  { fileName: "Octopus Tentacle Purple.PNG", name: "Octopus Tentacle Purple" },
  { fileName: "Plaque Problem.PNG", name: "Plaque Problem" },
  { fileName: "Rainbow Teeth.PNG", name: "Rainbow Teeth" },
  { fileName: "Ruby Studded Teeth.PNG", name: "Ruby Studded Teeth" },
  { fileName: "Sandwich.PNG", name: "Sandwich" },
  { fileName: "Seaweed.PNG", name: "Seaweed" },
  { fileName: "Shark.PNG", name: "Shark" },
  { fileName: "Toothy Grin Jeweled.PNG", name: "Toothy Grin Jeweled" },
  { fileName: "Toothy Grin.PNG", name: "Toothy Grin" },
];

export const shorts = [
  { fileName: "Blue And White Stripes.png", name: "Blue And White Stripes" },
  { fileName: "Building Blocks Aqua.PNG", name: "Building Blocks Aqua" },
  { fileName: "Building Blocks Golden.PNG", name: "Building Blocks Golden" },
  {
    fileName: "Building Blocks Gray Red.PNG",
    name: "Building Blocks Gray Red",
  },
  { fileName: "Camo Fuchsia.png", name: "Camo Fuchsia" },
  { fileName: "Camo Green.png", name: "Camo Green" },
  { fileName: "Colorful Flowers Blue.png", name: "Colorful Flowers Blue" },
  { fileName: "Colorful Flowers Purple.png", name: "Colorful Flowers Purple" },
  { fileName: "Cutoff Jeans.png", name: "Cutoff Jeans" },
  { fileName: "Flames.PNG", name: "Flames" },
  { fileName: "Flamingo Dark.PNG", name: "Flamingo Dark" },
  { fileName: "Flamingo Light.PNG", name: "Flamingo Light" },
  {
    fileName: "Fossil Skull Red And Yellow.png",
    name: "Fossil Skull Red And Yellow",
  },
  { fileName: "Fuku Burger.png", name: "Fuku Burger" },
  { fileName: "Plaid.png", name: "Plaid" },
  { fileName: "Rainbow.PNG", name: "Rainbow" },
  { fileName: "Starfish Green And Blue.PNG", name: "Starfish Green And Blue" },
  { fileName: "Starfish Orange.PNG", name: "Starfish Orange" },
  { fileName: "Stripes Green And Aqua.PNG", name: "Stripes Green And Aqua" },
  { fileName: "Stripes Red And White.PNG", name: "Stripes Red And White" },
  { fileName: "Tropical Graphic Green.PNG", name: "Tropical Graphic Green" },
  { fileName: "Tropical Graphic Yellow.PNG", name: "Tropical Graphic Yellow" },
];
